sudo: false
language: node_js
node_js:
- '5.1'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env: CXX=g++-4.8
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/bin/cordova
    - $(npm config get prefix)/bin/ionic
install:
- npm install -g cordova ionic@beta
- npm install
before_script:
- wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
- tar -xvf android-sdk_r24.4-linux.tgz
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2
script:
- ionic state restore
- ionic build android
deploy:
  provider: releases
  api_key:
    secure: CJQHhFmlnwGmqfnMzM4I0WC37V8YforkUoeArJXHzLMNNRmfSbDHKs3MDMQg4MFZzTOtEq2hKya1v7PaAxAempjkX3GoIGuhqP1q7f86U2gi89Fd0aNwjiusKkFvib6xDctGSetY3FyK6/QrWpy/dTFG2LIfW+MtomVMfOEjT5JLrjwPGDyZ9jbn4beBUMtRdFt/wYtSfN/Im0es0c+CRsgc8UfdoWXgmsdl+nEB5WJaq3LkG7y82HdAFKaYI8uB4tRkf7rQveaSIYgRCgIjexOMVBL0gJPIjarkjhYPnAqOF3fjvFehDcSbSBFNX9mHVvsOFvCdkjht6Ri7c7gW/05WiHfWaDyZ8hbXOAjFgUqdPKiDXVuADNnL29KywDpxfVIi+rUA1fd2Oosjfr54kzq7ox291dSkbANUuPK/DBiDNQVKM0AVi4WnC7u1P4ACBMajY+XtKa/lwBFaG8FNeekPHLJ5C/hNYuqq7/U9BQFmzcv4WE6z9NqAn296dwqXqDZ7Oak3ElBImvTVFzQoyxJJB4vxE3jkzYFo8WtictPDyZPA2Zg0SaZTiseQkXJt7YyWKFAQGjQwNjXpuTAs/t+n3mxmlfqIOperR4bnUNmqjgTYPAHHSeAMfLtpP/UeBfXqR6B7CS0BUzjZODfdJvqUPaa0QT0gpgMnfwxygKs=
  file: ./platforms/android/build/outputs/apk/android-debug.apk
  skip_cleanup: true
  on:
    repo: logikt/BloodApp
